### ISSUE TITLE
Could you make your theme avaliable in Cinnamon?

### ISSUE THREAD

**Issue by giwhub** [tista500/Adapta#1]
Hello,
Could you make your theme avaliable in Cinnamon?

**Comment by djendreizak** [comment]
That would be great

**Comment by tista500** [comment]
@giwhub,
@djendreizak,

Unfortunately I've never tried Cinnamon desktop, so later I will start implementation for it...
Please keep this issue open until I've finished to prepare for merging into master.

Regards.

**Comment by giwhub** [comment]
@tista500,

I have an idea:

If you make a light version with colorful metacity(
http://gnome-look.org/content/show.php/Libra?content=167689),that would be nice.

What do you think?

**Comment by tista500** [comment]
@giwhub,

> If you make a light version with colorful metacity

Please let me be clear that was related to the implementation of Cinnamon theming?
If not, stay on the topic please...

My Adapta theming guile-line is based on Material-Design's one. Recently I've unveiled raised & coloured "Close" button in master though, this is because the action of 'window close' should notify us carefully as highest priority before pressing button. But the others, 'minimize', 'maximize' and 'appmenu' should do as well? I don't think so... 

And I also dropped light variant header-bar and titlebar from all of window managers. I know many people would like to use light variant titlebars in other themes, however, today Adapta has dark variant Gnome-Shell , Budgie and Gnome-Flashback theming, if so, most users can concentrate the *contents* of its windows than light variant window frames. For example, many people runs dark variant media player applications to watch movies, and lots of hard punchers will use dark variant terminal applications, isn't it? Then the combo dark variant panel and light variant header-bar might have unexpected *intense* contrast between them. As known well, titlebars and header-bars are the important pieces of window frame, but I think those are handlers/controllers instead...

Anyway if most of users would like to revert to light variant titlebars and header-bars, I will surely do so. :smile: 

Regards.

**Comment by tista500** [comment]
Greetings,

Today I've committed Cinnamon 2.8.x theming into Master and 3.18.x branch although I did not test it well...

So just closed this issue.

**Comment by marmistrz** [comment]
The Adapta GTK theme is not visible in the Cinnamon themes app. Only the status bar theme can be chosen.

**Comment by tista500** [comment]
@marmistrz,

It's Cinnamon bug.
From Gtk+ 3.16 or higher, we could have multiple versioned themes but Cinnamon did not improve that feature (Cinnamon desktop system is pretty aged for me). So use Gnome-Tweak-Tool.
I don't know Cinnamon 3.0 could implement that feature in their development cycle...

Regards.
