### ISSUE TITLE
Share more code between gtk versions/desktops

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#101]
I thought about making a variant of adapta (nokto) with a different color palette.
Looking at the code (_colors.scss and friends) I've seen that the file is mostly duplicated across GTK versions and different desktops. And when looking at the commit history you often commit the same change to different directories.
Would it be possible to extract more commonalities out in order to have less duplicated code and thus easing customization? Given that you are already using a CSS preprocessor.
I haven't looked too much into it, so sorry if this is obviously not possible.

**Comment by tista500** [comment]
In technically, it's possible, but I dislike to do like that. Because those "regardless" sharing sometimes are wasting my time to debug.

Finally, if you want to making *your* own thme, please DO NOT NAME it "Adapta". Once you had changed colour palette, it became something but Adapta. And stop asking me to help debugging.

Regards.

**Comment by pschichtel** [comment]
> In technically, it's possible, but I dislike to do like that. Because those "regardless" sharing sometimes are wasting my time to debug.

Can you elaborate on that? From the viewpoint of a software developer, reducing code duplication would improve the debugging experience (less code to look at).

> Finally, if you want to making your own thme, please DO NOT NAME it "Adapta". Once you had changed colour palette, it became something but Adapta. And stop asking me to help debugging.

Of course I wouldn't call it Adapta.

**Comment by tista500** [comment]
Oh I understood you are may be a famous and great Web/CSS designer...

But unfortunately I am very foolish and my codes are quite bad. Yeah because I'm idiot I need to spend so long time to change colour palette. In a daylight, or midnight, 2 tablets, 4 laptops, 2 desktops are needed to introduce, check, verify, review and commit... I believe colour scheme design is strongly related to psychology and feelings when people see the colours, so I've spent much time to decide them.

So I suppose there's nothing to tell you. Yeah it looks like elementary school student teaches physics to Ph.Ds. :)
I know you don't need any help form me like a fool.

Regards.

**Comment by pschichtel** [comment]
I don't think there was a reason to be aggressive, at least no offense was intended and I'm sorry if did unknowingly.
I still don't get the exact reason, but at least the answer to the issue is clear: No, you will not deduplicate your code.
