### ISSUE TITLE
adapta theme pixelise my desktop

### ISSUE THREAD

**Issue by Cherkah** [tista500/Adapta#115]
**Reporter info**

 ```
 * Distribution - debian testing
 * Gtk+ 3.0 version - 3.20-4.1
 * Desktop environment - gnome 3.20.2
 ```

**Adapta version (if you knew)**

adapta clone master

**Related Application and/or Shell theming (or name of widget)**

GNOME Tweak Tool - adapta/adapta-nokto

**Actual issue**

see the pictures

![capture d ecran de 2016-05-27 02-32-11](https://cloud.githubusercontent.com/assets/16431970/15600467/ff8534d8-23b7-11e6-9b15-8261045bd428.png)

![adapata2](https://cloud.githubusercontent.com/assets/16431970/15600458/ee7966d2-23b7-11e6-9a8f-5511589ba4cf.png)

![adapta1](https://cloud.githubusercontent.com/assets/16431970/15600461/f2302766-23b7-11e6-9812-11db7ff367af.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

got a normal rendering

**Other Note (feature-request, question, etc...)**

does it the actual version of gtk2-engines-murrine (0.98.1.1-5 in testing) which gives me this probleme?

**Comment by tista500** [comment]
@Cherkah,

Answer my questions:

* Why top-bar has vertical gradient, Gnome-Classic or not?
* What font you use as interface.
* Why dash was placed to right-most side, your locale has RTL?

> does it the actual version of gtk2-engines-murrine (0.98.1.1-5 in testing) which gives me this probleme?

I don't think so because murrine nerver affect to Gnome-Shell components.

Regards.

**Comment by tista500** [comment]
One more.

Let me know your font-list:
```
dpkg -l | grep 'fonts-' | awk '/ii/{print $1,$2,$3}'
```

Regards.

**Comment by Cherkah** [comment]
**dpkg -l | grep 'fonts-' | awk '/ii/{print $1,$2,$3}'**:
ii fonts-cantarell 0.0.24-1
ii fonts-dejavu 2.35-1
ii fonts-dejavu-core 2.35-1
ii fonts-dejavu-extra 2.35-1
ii fonts-droid-fallback 1:6.0.1r16-1
ii fonts-freefont-ttf 20120503-4
ii fonts-lato 2.0-1
ii fonts-liberation 1.07.4-1
ii fonts-noto-mono 20160116-1
ii fonts-opensymbol 2:102.7+LibO5.1.3-1
ii fonts-sil-gentium 20081126:1.03-1
ii fonts-sil-gentium-basic 1.1-7
ii xfonts-100dpi 1:1.0.4+nmu1
ii xfonts-75dpi 1:1.0.4+nmu1
ii xfonts-base 1:1.0.4+nmu1
ii xfonts-encodings 1:1.0.4-2
ii xfonts-scalable 1:1.0.3-1.1
ii xfonts-utils 1:7.7+3

**Why top-bar has vertical gradient, Gnome-Classic or not?:**
 vertical gradient is due to  _## dynamic top bar_ ( a gnome shell extension).
gnome-shell



**Why dash was placed to right-most side, your locale has RTL?**
dash on right side is due to  ## _dash to dock_ ( a gnome shell extension)

**Comment by tista500** [comment]
Thanks.

As of your font-list, Adapta pulls "Lato" as primary font in Gnome-Shell because Adapta has this white-list: `Lato, Roboto, Cantarell, Sans-Serif` in `$font-family`.

Then lots of settings of "font-binding" are placed in `/etc/fonts/conf.d`, so you had proper biding to be suitable for your current locale (or custom file in `$HOME/.fonts.conf` or `$HOME/fontconfig/fonts.conf`)?

I suspect this issue was caused by locale problem that Lato might loose some bindings. For example, Cantarell has its own configuration in `/etc/fonts/conf.d/31-cantarell.conf`. In general, Cantarell only has "weak" binding, so in most cases of "non-English" locales, Cantarell will be replaced with "locale specific" font-family.

So let's do an easy test:
1. open stylesheet (example: Adapta): Use your favorite editor to open file installed in `/usr/share/themes/Adapta/gnome-shell/gnome-shell.css`
2. Edit like this:
```diff
@@ -25,9 +25,9 @@
   transition-duration: 0.2s; }
 
 stage {
-  font-family: Lato, Roboto, Cantarell, Sans-Serif;
+  font-family: Cantarell, Sans-Serif;
   font-weight: 400;
-  font-size: 10pt;
+  font-size: 9pt;
   color: #263238; }
 
 /***********
```

  * When using Cantarell, 9pt might be better than 10pt...

3. Save and close. Then type"Alt + F2" to open run-dialog, and type `r` and hit "Enter" to restart Gnome-Shell.

So fonts can be rendered as you expected? Please try this at first.

Regards.

**Comment by Cherkah** [comment]
thanks tista500 
 you was right .. 
the changes only on -  font-family - was sufficient to correct the fonts issues. 
 nice work 
  regards

**Comment by tista500** [comment]
OK. Good...

Then let me know your current locale and "actual" font-name should be used in Gnome-Shell. I will include it in Master to override other font-family...

Regards.

**Comment by Cherkah** [comment]
current locale:
LANG=fr_FR.UTF-8
LANGUAGE=fr_FR:fr
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"

 font-name: cantarell regular 12

you wellcome

**Comment by tista500** [comment]
@Cherkah,

I've just now installed
```
language-pack-fr
language-pack-fr-base
language-pack-gnome-fr
language-pack-gnome-fr-base
```
and then run `sudo update-locale LANG=fr_FR.UTF-8 LANGUAGE=fr_FR:fr`:

![capture du 2016-05-28 03-12-32](https://cloud.githubusercontent.com/assets/6073622/15617213/d8f026fe-2482-11e6-947d-3810bedb1c70.png)

Seems Lato could be rendered correctly without any tweaks... :(
I could not reproduce your issue in my PCs.

It's weird.

**Comment by Cherkah** [comment]
and i can not help you to find any kind of keys of research to reproduce this issue.

weird ? maybe !
 lets an other one pointing out same thing to center this trouble and override master.

**Comment by tista500** [comment]
I can't fix this if it could be reproduced.

Closed.
