### ISSUE TITLE
Unreadable text in Firefox on global dark theme

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#13]
This probably effects other GTK based browsers as well.
Many websites assume, that input fields have a light background and a dark foreground. This assumptions breaks when enabling the global dark theme.
So many websites change the foreground color, but keep the background to default or just change the background color and keep the foreground to default.

Is there anything the theme could do about that?

**Comment by tista500** [comment]
@pschichtel,

This is the good question.
And I'm wondering many Gtk+ theme designer might be troubled such issues for many years...

> This probably effects other GTK based browsers as well.
I suppose this commnet seems 50% right, and 50% wrong. Because the 'Rendering Engine' intervenes between Gtk ToolKit and HTML. So even if we used exactly same Gtk+ theming, the result (appearance) would be different.

For example, here's my Launchpad page,
1. GtkEntry text rendered by Gecko on Firefox Gtk+3 version-ed:
![screenshot from 2016-03-04 01-01-23](https://cloud.githubusercontent.com/assets/6073622/13500773/51d84caa-e1a7-11e5-9784-315fe2f49b00.jpg)

2. GtkEntry rendered by WebkitGtk2 on Epiphany:
![screenshot from 2016-03-04 01-03-56](https://cloud.githubusercontent.com/assets/6073622/13500812/8091394e-e1a7-11e5-9a38-5dd54b64755e.jpg)

You can see the difference where a red arrow pointed to. Indeed, both GtkEntry looks ugly but Webkit seems to try to convert colour schemes properly than Gecko...

Anyway if I set 'solid white' background and 'solid black' foreground into dark variant, this issue would be fixed. However, I now think that rough workaround may break any other GtkEntry's design, so I need much more time to fix this, please... At first, I have to determine which style-class can be accepted for raised (solid) GtkEntry design only inside the GtkScrolledWindow... :smile: 

Regards.

**Comment by pschichtel** [comment]
It's in no rush, take your time :)

The issue is so far present in every theme I tried, including the Adwaita default theme.
I can also confirm, that it does not happen in webkit browsers

**Comment by pschichtel** [comment]
Wouldn't it be possible to apply these styles only to elements in a Firefox window? The paper theme for example applies different header colors to certain applications.

**Comment by tista500** [comment]
As this report: https://bugzilla.mozilla.org/show_bug.cgi?id=70315 , It would be impossible without  custom css for Firefox (but in my some tests, firefox-trunk would not work with such css inside the '~/.mozilla` direcotory).

So I will give this trying up now. Because GtkInspector could not help to track this issue down anymore, and "MozContainer" is out of control from any Gtk+ theming.

In downstream, like me, there's nothing to do with it now.

Closed.

Regards.
