### ISSUE TITLE
[Gtk+ 3.x][XFce4] High CPU usage

### ISSUE THREAD

**Issue by leshniak** [tista500/Adapta#130]
**Reporter info**

 ```
 * Distribution - Debian
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - Xfce
 ```

**Adapta version (if you knew)**
3.21.2

**Related Application and/or Shell theming (or name of widget)**
-

**Actual issue**

High CPU usage

**Steps to reproduce (if you knew)**

Set Adapta as desktop theme

**Expected behaviour**

Lower CPU usage

**Other Note (feature-request, question, etc...)**

My Xorg process goes to the top if I set Adapta theme (even 50% cpu sometimes), on other themes seems to be ok. Maybe sth with gtk2-engine-murrine?

**Comment by tista500** [comment]
@leshniak,

Hey, XFce4 supports multiple-versioned Gtk+ theme?
Now Adapta uses Gtk+ 3.20 specific theming in specific directory instead of `gtk-3.0`. And I did not see any high-loads in other DEs and the combo "Gtk+ 3.18.9 + XFce4 4.12.2" ... :(

Wasn't XFce4 specific issue related to its own codes?

Regards.

**Comment by tista500** [comment]
Edited the title...

**Comment by leshniak** [comment]
I don't how it works, sorry. My previous theme is not compatible with GTK 3.20 and doesn't style windows, so I decided to change my theme to this one (good work btw). But CPU usage jumps sometimes - Xorg is on top, I didn't notice that on Adwaita for instance.

**Comment by tista500** [comment]
If murrine engine had a performance regression in your case, check Arc theme as well. Arc also uses murrine engine...

Still Adapta eat resources in XFce4 much more than Arc?

Regards.

**Comment by tista500** [comment]
Closed at this time, if someone had similar issues, I will re-open it...

Closed

**Comment by cameronleger** [comment]
I have some more informaton on this issue and can confirm it affects me as well with a similar setup:
Adapta: 3.21.5.2
GTK: 3.20.9
Murrine: 0.98.2
XFCE: ~ 4.12.3

Similar performance hit happens with Flat-Plat 3.20.20160821, however it does not happen with 3.18.20160821. I do not see large differences between those versions, so I am using 3.18 for now. Seems to be an issue stemming from GTK3 versions, so I'm hoping that when 3.22 is released this may be resolved.

I tried compiling with the --disable-gtk_next flag, but that did not solve the performance hit.

I can provide any more information as requested.

**Comment by tista500** [comment]
Anyone knows which components were related to this issue? xfce4-panel? xfwm4? or others? :(

Regards.

**Comment by cameronleger** [comment]
I've moved to a hybrid XFCE/i3 setup and I no longer have the issue. However, xfce4-panel is at least one of the culprits. If I start that then the CPU usage for Xorg immediately goes to ~12% (from <1%) and overall CPU usage is ~40% on all cores (from ~3%). I cannot reliably start xfwm4 from i3, but I can try later to switch to an XFCE session and see if running that without a panel causes any issues.

I don't think compositing is another culprit, but I am using compton 0.1_beta2.5-3 instead of XFCE's. I've tried this on an Intel Integrated Graphics chip and an NVIDIA GPU, both with and without compton running with the results being the same.

And regarding earlier comments, the only two themes I've seen this issue on is Adapta and Flat-Plat. I've tried all of the other bundled XFCE themes and a few others such as Arc and Numix. Perhaps the issue stems from Flat-Plat?

**Comment by tista500** [comment]
@cameronleger,

Sounds strange... o_O
Since Flat-Plat does not have any XFce4 specific theming, it means XFce4 has some incomplete portings to Gtk+ 3.x in the code-base instead of "theming".

> fce4-panel is at least one of the culprits. If I start that then the CPU usage for Xorg immediately goes to ~12% (from <1%) and overall CPU usage is ~40% on all cores (from ~3%).

This might be known issue of xfce4-panel's plugins. Most case some indicators triggered those jumping CPUs and those are not the issue of Gtk+ theme.

Regards.

**Comment by tista500** [comment]
Fix incorrect selector for `xfce4-panel` class: https://github.com/tista500/Adapta/commit/2b695aeb1b0f131ec65393aad39e221166a700aa

I'm not sure that incorrect selector was related to this issue though...

Regards.

**Comment by tista500** [comment]
@cameronleger,

Just to clarify:
> Similar performance hit happens with Flat-Plat 3.20.20160821, however it does not happen with 3.18.20160821. I do not see large differences between those versions, so I am using 3.18 for now. Seems to be an issue stemming from GTK3 versions, so I'm hoping that when 3.22 is released this may be resolved.

I could not get the point. it meant that you tried Gtk+ 3.18.x theming onto Gtk+ 3.20.x? If true, I don't know what you want to do... Because there's no compatibility between 3.18.x theming and 3.20.x one. And it causes tons of "Theme parsing errors...". If this happened some of GtkWidgets are not themed or incorrect theming are applied.

Or if you downgraded Gtk+ to 3.18.x and then applying 3.18.x theme, CPUs usage might be reduced. Because some theme designers (me, too) had added many of newer features into Gtk+ 3.20.x theming since 3.20.x has very helpful implementations to create new generation Gtk+ themes (But some designers might not do though)... So yeah 3.20.x theming will eat resources obviously than 3.18.x, especially in Adapta, too...

Regards.

**Comment by cameronleger** [comment]
You are correct in your assumptions, but maybe you'll have to forgive me. I'm familiar with development, although not specifically with Gtk, and I was assuming that there weren't large or incompatible changes between 3.x. I guess that would only be true of the 3.x.y versions, though. In any case, yes I left my Gtk at 3.20.9 - latest on Arch's main repos - and installed the Gtk 3.18.x theme of Flat Plat. As I said, I didn't notice large changes in the UI, so I ran with that one for a while because it didn't eat the CPU.

Also, you were right to narrow it down to panel plugins. I started xfce4-panel and removed the one panel that wasn't only launchers, and the CPU usage returned to expected usage. I tried adding each of the items to the panel and found two that seem to be the culprits:
xfce4-pulseaudio-plugin 0.2.4-1
xfce4-power-manager 1.6.0.41-g9daecb5-1

In the end, perhaps it's the case that the bugs are in those projects (or XFCE which isn't totally on Gtk3), and something that you're doing just makes them surface. A quick search didn't come up with anything specific that can help, although here's a few similar problems from recent posts. They did tip me off to a 'fix,' though, by setting the Panel's Style to either Solid Color or Background Image the CPU usage 'leak' disappears. It's only apparent with the System Style option.

https://bbs.archlinux.org/viewtopic.php?id=217106
https://aur.archlinux.org/packages/xfce4-pulseaudio-plugin/

**Comment by tista500** [comment]
I don't know what's new in XFce4 4.13, but hopefully panel could be constructed with Gtk+ 3.x only (now 4.12.x may mix the 2.x and 3.x?).

And agreed:
> I started xfce4-panel and removed the one panel that wasn't only launchers, and the CPU usage returned to expected usage. I tried adding each of the items to the panel and found two that seem to be the culprits:
xfce4-pulseaudio-plugin 0.2.4-1
xfce4-power-manager 1.6.0.41-g9daecb5-1

I've also experienced high CPUs usage with pulseaudio-plugin. This might be the main reason why Arch still employs legacy volume-applet...

Regards.

**Comment by lithces** [comment]
When using Adapta, after removing pulseaudio-plugin from xfce4 panel, the CPU usage becomes normal.

The CPU usage is OK with other theme (like Arc) even with pulseaudio-plugin enabled in the panel.


My system config is listed below,

 * Distribution - Fedora 24
 * Gtk+ 3.0 version - gtk3-3.20.9-1.fc24.x86_64
 * Desktop environment - xfce4-session-4.12.1-9.fc24.x86_64

Adapta version (if you knew)

3.21.6, installed from 'Copr repo for gtk-themes owned by heikoada' via dnf

**Comment by PyGeek03** [comment]
I can confirm that quitting the xfce4-panel reduces Xorg's CPU usage immediately.

**Comment by tista500** [comment]
I've added some "disabling features" (I really didn't want to do). :/

https://github.com/tista500/Adapta/commit/bb7f690435e839847924caeef5aecdd8c7a0fdad
https://github.com/tista500/Adapta/commit/ac3079248d4c7e11081bc0dab1bb0e559e381686

Mixed Gtk+ versioned panel are really needed?? I hope those commits could finish this barren backward-compat. discussion...

Regards.

**Comment by tista500** [comment]
And one more: https://github.com/tista500/Adapta/commit/a2ad406f8c4252ce25383c4a4331b0c080412a8d

**Comment by tista500** [comment]
Today I've checked xfce4-panel 4.12.0 and pulseaudio-plugin 0.2.4 with Gtk+ 3.22.1, then jumping CPUs usages are almost fixed? At least, when idle, most of processes seem to mark very low usage...

Regards.

**Comment by tista500** [comment]
The final one: https://github.com/tista500/Adapta/commit/5ec42ac098e4686dab08362878a360fa96b7f4ef

I suppose this issue seems to be fixed almost, so closed once again...

Regards.

**Comment by LZL1** [comment]
In any case there is something wrong.
Look at similar issue:
[https://bugs.launchpad.net/ubuntu/+source/xfce4-indicator-plugin/+bug/1583164](url)

**Comment by tista500** [comment]
@LZL1,

??
The issue was fixed in Adapta, so what did you want me to do?
Removing indicators/plugins is not workaround but useful when tracking issue. The main reason of jumping CPUs is related to transition/animation property in button node on Gtk+ 3.x. It should be fixed in upstream (though we, theme designers can fix it by disabling transitions/animations on button node styling), because this issue only happens on xfce4-panel as far as I know.

**Comment by sadalsuud** [comment]
Again in xubuntu 18.04 High CPU usage, when I change theme, CPU usage decreases
/usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswith
is the proccess get me problem
Any idea ...

**Comment by philmmanjaro** [comment]
@sadalsuud : please test revision 42 of the current 3.94.0 series.
