### ISSUE TITLE
Black line between window decoration and menu bar

### ISSUE THREAD

**Issue by tliron** [tista500/Adapta#138]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**

Commit c6f7949

**Related Application and/or Shell theming (or name of widget)**

e.g., GNOME Terminal

**Actual issue**

Applications with client-side decorations have a nice thick bar at the top (e.g, Nautilus). But other applications (e.g. GNOME Terminal) show a distinct divider between the decoration and the menu bar.

**Other Note (feature-request, question, etc...)**

I love that you allowed us to change colors!!! My wish is that we could also change the color of the X close button.

**Comment by GhettoGirl** [comment]
See #124, sounds familiar to this issue.
TIP: Screenshots would help out.

**Comment by tliron** [comment]
Actually, I have no problem with Nautilus. Attached is a screenshot.

![adapta](https://cloud.githubusercontent.com/assets/1146849/16249858/9f7591a6-37de-11e6-85de-16fce2956225.png)

**Comment by tista500** [comment]
In case neither 'maximized' nor 'tiled', Mutter's window-frames should be drawn in higher elevation than GtkMenuBar.

**Comment by tliron** [comment]
My apologizes, but I don't understand your comment. Are you saying that this is not a bug, that it is by design? I think it's not very consistent: in applications that have client-side decorators, you get one thick bar, but in applications with menu bars, you get two bars like this.

Note that in many themes the bars merge. For example, see Arc theme.

**Comment by tista500** [comment]
Why I should mimic Arc? Why quite different elements are merged?

**Comment by tliron** [comment]
You absolutely do not have to mimic Arc! :) If this is your design, then you should close this issue. I thought this was unintended, which is why I opened this as a bug.

In my _personal_ opinion, it does not lead to a consistent desktop experience. To me, the menu bar is part of the functionality of the top bar, in the same way that client-side decorations merge that functionality more directly into the title bar. That dividing line makes these applications look too different. Material design, too, puts an emphasis on merging elements of the same color/functionality.

I would also be happy if you provided a autoconf option to allow merging the two!

By the way, I included Adapta in my [GNOME themes script](https://github.com/tliron/install-gnome-themes). I think it is utterly gorgeous and I love the fact that I can change the colors! A lot of work went into allowing for that!

**Comment by tista500** [comment]
> In my personal opinion, it does not lead to a consistent desktop experience. To me, the menu bar is part of the functionality of the top bar, in the same way that client-side decorations merge that functionality more directly into the title bar. That dividing line makes these applications look too different. Material design, too, puts an emphasis on merging elements of the same color/functionality.

In Material Design, there's no materials that has only text-label based tool widget beneath the Toolbars like GtkMenuBar. If you meant 'stack-switcher' style, it's quite different purpose, different design.

And GtkMenuBar is not the part of Mutter/Metacity. GtkMenuBar is the floating tool widget and those never include window-manager's tools but include the tools of 'window contents'. So GtkMenuBar can be placed (embedded) into various types of widgets, that's the advantage of floating tool widget. And I don't think server-side decorations does have to have the same element design with client-side decorations. On the other hand, GtkHeaderBar is the composited tool widget which includes both window-manager's tools and window-content's tools in the same depth, same elevation. So Adapta doesn't have any tool-separators inside the GtkHeaderBar (Of course GtkPaned was drawn with separators because that separator is for dividing multiple GtkHeaderBars).

In case when GtkWindows are 'tiled' and/or 'maximized', Adapta falls down the depth-level of Mutter's window-frame and GtkMenuBar to the "depth-0" ( Mutter was 2-levels down and GtkMenuBar was 1-level down). This is because tiled/maxd modes are no longer 'raised' materials (means 'move' and/or 'resize' actions are not needed anymore until untiled/unmaxd). This is the special case that SSDs and GtkMenuBars are in the same elevation.

So for me, your opinion might sound slightly different with mine (my design concepts).

Anyway I will re-read this when doing overhaul the design...

Regards.
