### ISSUE TITLE
PCManFM Theming

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#159]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - Xfce4
 ```

**Adapta version (if you knew)**  3.21.3.56

**Related Application and/or Shell theming (or name of widget)** PCManFM

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)** Can you theme PCManFM a bit? I'd like to see something (like a dark line) near the side pane so it doesn't blend with other things (like the toolbar). There is a line near the side pane but it's too faint. Thank you!

![screenshot from 2016-07-04 16-36-04](https://cloud.githubusercontent.com/assets/18717816/16562619/8ce4f5d6-4206-11e6-994d-4c48191dc545.png)

**Comment by tista500** [comment]
Why that file-manager was needed in XFce4?
Thunar is the default one of XFce4, and I won't support LXDE since devs already planned to move to Qt toolkit, so why today I have to support ancient Gtk+ 2.0 theming for PCManFM? :(

Anyway partially supported theming was added: https://github.com/tista500/Adapta/commit/a8b5c84bf5c1b7092c54c424bb29d2319de03091

Regards.
