### ISSUE TITLE
Old releases removed

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#19]
Currently when you're creating a new release you also remove the old one (so you basically replace them). This will cause package definitions to break as soon as you do a new release until the definitions have been updated. I usually update the archlinux AUR package within a day or two, but the situation is not optimal (comments at https://aur.archlinux.org/packages/adapta-gtk-theme).

My suggestion would be: Keep old packages for a period of time to give package maintainers a chance to update the defintions.
I think you could even just keep all versions as their size is small.

As a last option on my side: I could identify a version by its commit and pull the commit snapshot as the download instead of the release.

What do you think?

**Comment by tista500** [comment]
@pschichtel,

I don't know how AUR treated source archives at all though, why didn't you use git pulling to create source archives!?

Anyway remained previous releases are completely meaningless in most cases of Gtk+ theming, and for me as well. Because in Gtk+ theming, most users did not want to track down with bisecting between current and previous. That job is only for developer(s) (or team), but in usual, developers and contributors don't do wgetting release zip, just live with git instead.

Hmm, finally if you want me to keep the previous releases on GIt site, I will...

Regards.
