### ISSUE TITLE
Suggestion: Color

### ISSUE THREAD

**Issue by Nikki1993** [tista500/Adapta#2]
Just a suggestion as a material design freak (boy do I love it) maybe instead of yellow color on certain elements use teal instead? seems to kinda fit into the whole picture more than the yellow tint that looks a bit out of place, at least to me.

**Comment by tista500** [comment]
@Nikki1993,

> instead of yellow color on certain elements use teal instead

Adapta uses `Orange500` as *Dynamic information actors* instead of yellow. And `teal` is now popular colour on Android 6.0 or higher I know.

But please see carefully Android's overlay information bar. It still uses Orange (or dark Yellow) for  *suggested* actions like "UNDO" and/or so... Also in Adapta, I usually use `Orange` colour scheme as dynamic information indicators like message-dialog buttons, progress-bars, spinners and OSD elements, because those elements should be drawn with high contrast (opposed) colour against the dark-grey (used in dark variant) colour background. We can easily use `teal` for them, but once that happens, we may mis-recognize between `cyan` and `teal` (surely `cyan` is Adapta's key colour as of selection items). The dnyamic infomation (animation) should be drawn like "warning" actions, I just think...

Adapta's goal is not the complete mimic of Android, but optimization for Gtk+ and Gnome.

Regards.

**Comment by Nikki1993** [comment]
I completely understand and agree, however I can't help but to me orange feels out of place in this kind of color scheme. In the worse case scenario, fork and modify I suppose :D but thanks

**Comment by tista500** [comment]
@Nikki1993,

I've just now uploaded new colour-scheme introducing high-hue 'Teal' colours.
https://github.com/tista500/Adapta/tree/wip/teal-accents

But I don't know this could get more readability for OSDs, progess-bars and indicators...

Regards.

**Comment by Nikki1993** [comment]
@tista500 I switched to teal-accents branch and installed it on Gnome-Shell. 

Aesthetically, it looks a lot better than orange. It fits to the theme a lot better. 

Progress bar as teal seems to working out nicely as well. It's totally visible. I don't see any issues with indicators either.

One other thing which I would improve is increase the size of notification box when you receive a notification. Right now it seems to small. (but that's a different issue).

**Comment by tista500** [comment]
@Nikki1993,

OK.
Let's merge it into master...

> One other thing which I would improve is increase the size of notification box when you receive a notification. Right now it seems to small. (but that's a different issue).

I hope you could file a new issue for it (obviously I'd like to know which part of such tiny notification dialogs/popups is shown in Gnome-Shell, so any screenshots and actual codes would be appreciated)...

Anyway I just close this issue.

Regards.
