### ISSUE TITLE
[Request]  --with-foreground_color option for autogen?

### ISSUE THREAD

**Issue by pigeonlips** [tista500/Adapta#202]
**Reporter info**

 * Distribution - openSuSe
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3

**Other Note (feature-request, question, etc...)**

First up - Close this if you don't like it. Its you project and only a suggestion. I'm not going to take offence :smile: 

I think it sure would be nice if you could set the fg_color with an autogen option. 

I didn't like the Blue Gray for the background in the theme (this is a preference, nothing wrong with what you got here, Just wasn't too *my* taste). So, hope you don't mind, I forked and replaced the values from Grey in the [color pallet](https://material.google.com/style/color.html#color-color-palette). Must say am very happy with the result. 

Anyway, just an idea but maybe the background could become an option for autogen? 

If you wanted to go all out maybe all the items in the [color pallet](https://material.google.com/style/color.html#color-color-palette) are mapped somehow and you just pass in the color name to the option for automake. It could then work out the 500 and 300 values for you, I kinda imagine it like: 

> --with-selection_color=Cyan

rather than the current 

>  --with-selection_color=#00BCD4
>  --with-second_selection_color=#4DD0E1

Again, this is all just a thought. 

**Some love**

Great theme. Great work. I really like it.  :+1:  Thanks for making my desktop a happier place. 

much love

![image](https://cloud.githubusercontent.com/assets/9683809/17916552/5c071910-6a08-11e6-94e6-977cd9446b52.png)

**Comment by tista500** [comment]
Unfortunately I won't...
Sounds like you said "Rewrite 62,000 whole lines in SCSS and SVG/PNG files".
Because every borders, shadows are optimized my favorite BlueGray colour scheme, so once those has been changed, I need to re-define them from scratch.

> If you wanted to go all out maybe all the items in the color pallet are mapped somehow and you just pass in the color name to the option for automake. It could then work out the 500 and 300 values for you, I kinda imagine it like:

> --with-selection_color=Cyan
> rather than the current

> --with-selection_color=#00BCD4
> --with-second_selection_color=#4DD0E1

Oh no, 6HEXx is the best for developers and debuggers in Web design.
And your approach will need the table to generate 6HEXs from Name, it's really meaningless for me. We should not define colours with such 'fuzzy' name but precise HEX codes or simply rgba(xx,xx,xx,xx).

Anyway colour-changer for `background-color` would be interesting, but if changes had done, Adapta becomes something I don't know. And I also don't want to maintain "that thing" anymore.

Regards.

**Comment by pigeonlips** [comment]
Fair Enough. T'was easy to fork and change the values so I'm a happy man. Thanks for the great theme. 

I'll close this.
