### ISSUE TITLE
make: *** [install-recursive] Error 1 

### ISSUE THREAD

**Issue by amalshehu** [tista500/Adapta#219]
**Reporter info**

 ```
 * Distribution -	Ubuntu
 * Description:	Ubuntu 16.04.1 LTS
 * Release:	16.04
 * Codename:	xenial

 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.1
 * Gtk+ 2.0 version - 2.24.30-1ubuntu1 
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
        Adapta Gtk+ Theme 3.21.6

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
````
Making install in gtk
make[1]: Entering directory '/home/amalshehu/Adapta/gtk'
make[2]: Entering directory '/home/amalshehu/Adapta/gtk'
make[2]: Nothing to be done for 'install-exec-am'.
/bin/mkdir -p /usr/share/themes/Adapta
/bin/mkdir -p /usr/share/themes/Adapta-Nokto
/bin/mkdir -p /usr/share/themes/Adapta-Eta
/bin/mkdir -p /usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /usr/share/themes/Adapta
'./index.theme' -> '/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/bin/mkdir -p /usr/share/themes/Adapta/gtk-3.0
/bin/mkdir -p /usr/share/themes/Adapta/gtk-3.0/assets
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css /usr/share/themes/Adapta/gtk-3.0
cp: cannot stat './gtk-3.18/gtk.css': No such file or directory
cp: cannot stat './gtk-3.18/gtk-dark.css': No such file or directory
Makefile:1320: recipe for target 'install-data-local' failed
make[2]: *** [install-data-local] Error 1
make[2]: Leaving directory '/home/amalshehu/Adapta/gtk'
Makefile:1112: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/amalshehu/Adapta/gtk'
Makefile:360: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

````

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

I have installed all the dependencies as mentioned .Still the problem exists while installation.

**Comment by tista500** [comment]
Why don't you read the README? : https://github.com/tista500/Adapta#installation-from-git-source

**Comment by tista500** [comment]
> `cp: cannot stat './gtk-3.18/gtk.css': No such file or directory`

`make` was skipped? :(

**Comment by amalshehu** [comment]
Thanks a lot . I skipped the `make` command,That was the problem.

**Comment by anudeepch6789** [comment]
Starting RISC-V Toolchain build process

Removing existing riscv-openocd/build directory
Configuring project riscv-openocd
configure: WARNING: Info documentation will not be built.
configure: WARNING: libusb-1.x not found, trying legacy libusb-0.1 as a fallback; consider installing libusb-1.x instead
Building project riscv-openocd
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
Installing project riscv-openocd
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
Makefile:4383: warning: overriding recipe for target 'check-recursive'
Makefile:3794: warning: ignoring old recipe for target 'check-recursive'
/bin/mkdir: cannot create directory ‘/riscv’: Permission denied
make[3]: *** [install-binPROGRAMS] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

**Comment by anudeepch6789** [comment]
what i have to do now?
