### ISSUE TITLE
Tray icons are so small [Gnome 3.18]

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#24]
Hey, 
Thanks for your nice theme! looks really great on Gnome 
Just one small issue, the icons on gnome shell tray are so small (you can see that they're resized)
![capture du 2016-03-24 20-58-55](https://cloud.githubusercontent.com/assets/7660997/14029609/62a2ede4-f203-11e5-9e8b-20b08c17019a.png)
I don't have this issue with any other gnome shell theme.
Thanks again!

**Comment by tista500** [comment]
@bil-elmoussaoui,

I'm not sure what 'tray icons' were...
So please let me see how Adwaita showed them (as you expected?).

Regards.

**Comment by tista500** [comment]
Ah, you meant 'system-status-icon' size?

OK.
Now I've committed the fix: 2bba435ccc90d78bd2a51c26999c73db5b6a505d

I hope my fix could point to your issue properly...

Regards.

**Comment by bil-elmoussaoui** [comment]
Thank you! it's looking better now :+1: 
![capture du 2016-03-25 10-58-22](https://cloud.githubusercontent.com/assets/7660997/14042249/87cee1f2-f278-11e5-825a-9cf4b4f15343.png)
Just want to know why the system status icons are not white? or maybe the same color as the header bar? 
![capture du 2016-03-25 10-59-53](https://cloud.githubusercontent.com/assets/7660997/14042269/b6a7f46e-f278-11e5-8db1-b3042a111267.png)

**Comment by tista500** [comment]
@bil-elmoussaoui,

Good question.
This is the paradox between Gtk+ and Material Design.
Usually we won't care about "hover" action in any Android touch devices, right? Because Material Design does not to define "hover" action in any places, but in Gtk+, in most cases, we surely use mouse-pointer to do clicking, selecting, dragging and many actions. If so, Gtk+ should indicate us that mouse-pointer can be moved to actual "hover"-ed places, icons, buttons, and etc...

Generally "touch" obviously starts every actions from tap/swipe, but "mouse-pointer" does from move. So we should care about moving-in/out as hover action, otherwise we will lost the click-able elements.

In my Adapta, hovered icons and labels are highlighted in most cases to indicate hover/click-able. Means normal state is drown with around 10% darker, and hover state is done with almost white. Indeed, Adapta also has hover/active indicators in TopBar though, but I now don't think those are enough...

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for the clarification :+1:
