### ISSUE TITLE
Port it for Pantheon, pls

### ISSUE THREAD

**Issue by lababiba** [tista500/Adapta#29]
Port it for Pantheon, pls

**Comment by tista500** [comment]
@lababiba,

Please read this at first: https://elementary.io/us/docs/human-interface-guidelines#human-interface-guidelines
That is the HIG of elementaryOS.

I never think that HIG could accept for my design philosophy, Material Design Guidelines and Gnome HIG... The elementary devs have their own design rules and I don't want to work with their applications now. To be honest, Cinnamon and Unity, too. Because such situation just only makes tons of problems in visual appearances, workflows, and user experiences.

And in technically, elementaryOS employs ancient Gtk+ version (3.14 in Freya?), if so, I totally  have to write whole codebase from scratch. Gtk+ 3.14 was terrible for many Gnome geeks obviously (This is also the main reason why Cinnamon's apps looks bad).

I strongly suggest you should stay on the DanRabbit's default theme if you like elementaryOS, since it would be the best to work flawlessly...

Regards.

**Comment by tista500** [comment]
Now I'm a bit busy for integrating Gtk+ 3.20/21 so just close this issue in this time...

Regards.

**Comment by anaumidis** [comment]
Any update for elementaryOS Loki?

**Comment by tista500** [comment]
@anaumidis,

Which new features will be landed in Loki release?
I've read the blueprints but it seems to be unclear...

If they still employs these stuffs;
* Ubuntu-made indicators on WingPanel
* libunity dependencies
* Midori, Murine, and some elementary specific apps
* Left-most close button on Gala window-frames

I will not want to do integration for Pantheon shell...

Such their specific stuffs completely break our Material Design Guidelines, Gnome HIG, and my design philosophy. They just want to fork the benefits/results in Mac OSX, on the other hand, to be honest, I dislike OSX UI. And I don't want to put Adapta into their platform, too...

Regards.

**Comment by veluria** [comment]
Could you add support for transparency in pantheon terminal, perhaps? Other themes like Arc do.
