### ISSUE TITLE
Different color maximized titlebar?

### ISSUE THREAD

**Issue by ManjaroCinnamonFan** [tista500/Adapta#30]
Is there a reason for the titlebar (and headerbar) having different color depending on their state? Unmaximized windows are lighter than maximized windows.  This looks wrong, because it gives a two-tone-color when using (for example) the gimp in maximized state. The menu-bar is lighter than the titlebar. (using your 3.18 version on budgie)

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

This is because of 'chameleonic effect'. Since when maximized, window-frame does not have to have raised material. It means GtkHeaderBar goes down to zero-elevation. And you pointed Gimp, it's Gtk+ 2.0 application. In Gtk+ 3.0 apps, GtkMenuBar also got the same effect.

> This looks wrong,
I don't like such behaviour. Who judge it's right or wrong? If you dislike my theme, use others.

Regards.

**Comment by ManjaroCinnamonFan** [comment]
> I don't like such behaviour. Who judge it's right or wrong? If you dislike my theme, use others.
It's a great theme! I especially like the osd-shadow trick. Although it does not work all the time I appreciate the idea. As a themer myself I can appreciate the work you put into it...

**Comment by jose-sanchezm** [comment]
Is there any way to disable this effect?

**Comment by tista500** [comment]
@jose-sanchezm,

Rewrite SCSSs.

**Comment by jose-sanchezm** [comment]
I suppose there isn't any easy workaround then :(
Anyway, congratulations for your theme, it's beautiful. I suppose that there's the option of using Flat Plat for people like me who work continuously with maximized windows and don't like pitch black header bars.
