### ISSUE TITLE
Gnome Software has black text on dark background at inactive tabs

### ISSUE THREAD

**Issue by Corsseir** [tista500/Adapta#36]
As I said - just open gnome software and you will see the bug :) BTW, great theme.

**Comment by tista500** [comment]
@Corsseir,

As far as I know, there's no GtkNotebook's 'tabs' in Gnome-Software.
I suppose you meant 'stack-switcher' in GtkHeaderBar:
![screenshot from 2016-04-04 23-46-31](https://cloud.githubusercontent.com/assets/6073622/14251882/ea437a92-fabf-11e5-9adf-69819b039d4d.png)

If so, those ware already fixed in https://github.com/tista500/Adapta/commit/55cdc30010e10cd8c5cd0a33059b0cf0fed10ebc (Gtk+ 3.18.x) and https://github.com/tista500/Adapta/commit/2694940ebe100e6623b6439133bf91cd8325099f (Gtk+ 3.20.x).

Regards.
