### ISSUE TITLE
Shadow beneath headerbar not consistent?

### ISSUE THREAD

**Issue by ManjaroCinnamonFan** [tista500/Adapta#41]
I really like the shadow beneath the headerbar.  Unfortunately it doesn't seem to work on every applications (gtk-2-apps, terminal, gedit,...). Perhaps creating a shadow beneath the menubar in gtk2-apps? I've implemented that partially (in apps that show a toolbar beneath the menubar) by using a custom 'toolbar/inline-toolbar.png) that shows a shadow. Look at this: 
http://gnome-look.org/content/show.php/Mat-D+GTK?content=175344

But I didn't manage to get any further than that. I guess theming this is difficult? Any chance on improvement in that direction? Or is this low on the priority-list? 

By the way: I really love your theme. Using it on Ubuntu-gnome 16.04: works perfectly!

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

Good question...
OK. Let's explain the situation of Adapta.

1. Backgrounds
--------------------

In Material Design, we usually speak some words, "elevation" and "depth". Please read this first: https://www.google.com/design/spec/what-is-material/elevation-shadows.html#

2. Gtk+
---------

In Gtk+, most of users and developers did not concern that "elevations", so GtkMenuBar, GtkToolBar, GtkOverlay, and many elements are mixed into the single 'thick' elevations. For example, GtkMenuBar has higher elevation than GtkHeaderBar, it completely breaks our Material Design theming... More technically (precisely), drop-shadows exposed by GtkHeaderBar become underlay and are filled by  GtkMenuBar itself. This is why Adapta can't expose the GtkHeaderBar's shadow onto GtkMenuBar.
And GtkMenuBar doesn't have any features to expose its shadows to outside of it. This is why GtkToolBar can't be composited with GtkMenuBar's shadows.

My Adapta Gtk+ 3.0 theming also does not employ pixmap-based 'virtual shadows' instead of Gtk+ 2.0 and some elements of Gtk+ 3.0. I have some reasons not to use such pixmaps in Gtk+ 3.0 though... Anyway in my experiences, pixmap-based theming becomes **rasterized**, unscalable shadows. So Adapta Gtk+ 3.0 renders almost shadow parts as **vectorized** with Gtk+ 3.0 itself...

However, your issue is correct since we can draw (not expose) the virtual shadows onto GtkMenuBar and GtkToolBar with inset box-shadows. So I will do something to implement this features in both Gtk+ 3.0/2.0...

Regards.

**Comment by ManjaroCinnamonFan** [comment]
Thanks for the elaborate explanation!    

My trick with the use of a custom toolbar/inline-toolbar is (I admit) a unconventional one. But then I was thinking on a 'overlay'-pixmap onto the menubar itself (increasing the menubar-height first (somehow) and then use the extra space beneath the menubar-items to draw a pixmap that looks like a line with shadows under it....somehow... 
I know it is possible.  I did a rudimentary test.  It is possible to draw a pixmap on the menubar.  

But -as I said- it is hacking the theme crudely.  
And I think it is better to leave this Adapta-theme to the expert.

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

Implementation is started:

(Transmission with inset box-shadows on GtkMenuBar and GtkToolBar)
![screenshot from 2016-04-08 05-07-02](https://cloud.githubusercontent.com/assets/6073622/14365276/c6ab2f14-fd47-11e5-8937-de892bb649f7.png)

Regards.

**Comment by ManjaroCinnamonFan** [comment]
Amazing!  
It certainly looks better! And you have found a solution.  I hope you can implement it across all applications. Thanks for the quick response.  Awaiting the changes on your PPA.

**Comment by tista500** [comment]
OK. PPA is now pending to publish...

Check it out after 5 minutes or later...

Regards.

P.S
Those are very rough implementations so, it might have a couple of side-effects, maybe.

**Comment by ManjaroCinnamonFan** [comment]
Updated your theme and I wonder what you think of it yourself.  
You basically did the same things as I have done with my theme. And -thus- you run it to the same problems.
The Upside:
The shadows on the GtkMenubar gives the titlebar the headerbar-look.  Which I like. It gives it a more consistent look and at least you now have more applications where the shadow is seen. 
Some apps (like libre-office and inkscape) have  a double tool-bar.  So you have the shadow again in the second tool-bar.  As for me, I like it. It makes the double tool-bar easier to recognize.  
The downside:
First:Take -for example- Libre-office-writer: there are now 3 levels: titlebar/toolbar/ toolbar/work-area. That's allot of shadows.  It -kind of- contradicts your elevation and dept rules of material design. 
Second: The trick only works when there is a toolbar.  Which we knew of course.  Nevertheless it poses -a dead end-situation.  

So I was wondering if it were possible to create a inset-box-shadow-thing that would include the shadow that reflects on the white area beneath it, thus including the white under the shadow: see screenshot:
[Imgur](http://i.imgur.com/qqMng4R.png) 

All of the red area  would be the GtkMenubar background

This would imply : increasing the size of the menubar to make room for the shadow. 

The benefit would be that -because the shadow is included in the menubar itself- you would not need the inset-box-shadow on the GtkToolbar to create the effect. 

What are your thoughts on this?

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

> The shadows on the GtkMenubar gives the titlebar the headerbar-look. Which I like. It gives it a more consistent look and at least you now have more applications where the shadow is seen.

But as of Gtk+ application development, to be honest, it's "Don't Do" thing.
Because the titlebar rendered by Mutter is only just a part of Window-Frame, not a toolbox container. On the other hand, GtkHeaderBar is obviously container can contain various tool buttons, toggle menus, and window-manager buttons etc... If so, we should not elevate that Mutter's titlebar to the same depth of GtkHeaderBar, indeed, those are quite different materials.

> Libre-office-writer: there are now 3 levels: titlebar/toolbar/ toolbar/work-area. That's allot of shadows. It -kind of- contradicts your elevation and dept rules of material design.

At first, pealse do not confuse about LibreOffice. it's not Gtk+ application but Java eco-system. It's just only mimics the Gimp toolkit via extension. And every time it brings us the "half-baked" integration on both Gtk+ 2.0/3.0.
And back to topic, I think LibreOffice puts such GtkToolBar-like bars inside the single box container (GtkEventBox?), so drop-shadows should not be drawn on each bars (means those must be in the same elevation).
Finally I've reverted virtual drop-shadows inside the GtkToolBar of Gtk+ 2.0: https://github.com/tista500/Adapta/commit/019ecc3519457d10d5e41f5cc82f48a2f5d410ed
It's too problematic in Inkscape since it has vertical aligned GtkToolBars on the left/right side of window. Once top-to-bottom drop-shadows are appeared on such vertical GtkToolBars, 3D distortion happened (especailly on z-axis). So in this time, GtkToolBar in Gtk+ 2.0 went back to same-elevation with GtkMenuBar.

> Second: The trick only works when there is a toolbar. Which we knew of course. Nevertheless it poses -a dead end-situation.

Yes. but now we have almost moved to GtkHeaderBar. I really dislike GtkMenuBar and GtkToolBar. Those are always wasting vertical/horizontal working spaces in every situations. And those elements are not in Material Design UI, too. So I don't want to touch up those things any more... Especially, Ubuntu has been doing patchworks onto Gtk+ to force showing GtkMenuBar in a lot of applications because of Unity7. Such applications and desktop environments should be culled in the future, just my thought.

> So I was wondering if it were possible to create a inset-box-shadow-thing that would include the shadow that reflects on the white area beneath it, thus including the white under the shadow

No, impossible...
Because we can't prepare for all of elements and all of patterns of combination inside the GtkWindow beneath the titlebar and/or GtkHeaderBar.

> This would imply : increasing the size of the menubar to make room for the shadow.

Already committed: https://github.com/tista500/Adapta/commit/ff9ce7ae4695e1bfd3e53ee863cf8063cef47551


Regards.

**Comment by ManjaroCinnamonFan** [comment]
Allright, get your point.

Just tested my idea further (increasing the menubar_item  ythickness to 11) and redone the Z-dept-1.svg.  It is looking good on Gimp, L-office, Inscape. 
Screenshots: 
the background= 
[Imgur](http://i.imgur.com/EjfbTDx.png)

the result=
[Imgur](http://i.imgur.com/dngKAq5.png)

But I do not know if I should pursue down this road. It only works on GTK 2-draw applications.

**Comment by ManjaroCinnamonFan** [comment]
Updated your theme to the latest.  I thought you had removed the shadow on the GtkToolbar? Still shows on Transmission-app. Or is it still the purpose in this case?

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

Yes. I've purged virtual drop-shadows from Gtk+ 2.0 only.

> Just tested my idea further (increasing the menubar_item ythickness to 11) and redone the Z-dept-1.svg. It is looking good on Gimp, L-office, Inscape.

Well, You approach seems very hackish, then outset shadows are penetrated into GtkMenuBar  itself, right? If so, when we're changing the font size, the your pixmap's fixed-height causes visual glitches, since we can not set scalable units in any Gtk+ 2.0 widgets so.

So I think this issue seems to be fixed almost. If you want to do something more, I think you should contact to Matthias Clasen, Gtk+ lead developer...

Regards.
