### ISSUE TITLE
Close button a little pixelated in Cinnamon 

### ISSUE THREAD

**Issue by vibeast** [tista500/Adapta#47]
Is it my impression ?

Can it like gnome ?

![closebutton](https://cloud.githubusercontent.com/assets/18408100/14444064/ab964856-0019-11e6-8999-1d359d49dc09.png)

And this is happening in cinnamon 

![seetext](https://cloud.githubusercontent.com/assets/18408100/14444260/cdc5426e-001a-11e6-9ec6-2ee6d0bb20c2.png)

Thank you !

**Comment by tista500** [comment]
@vibeast,

Cinnamon integration is under work-in-progress.

> Can it like gnome ?

No. Because Cinnamon 2.8.x still stack with metacity theming method, so there's no way to render perfect vector-circle buttons like Gtk+ native engine.

> And this is happening in cinnamon

Known issue. This is because Cinnamon 2.8.x tries to render Buttons with Gtk+ theming instead of shell theming. Those message-diallog should be handled by shell theming, but they did not. The upstream bug I think. Or Nemo issue?

If Cinnamon 3.0.x had such stupid coding as well, I will purge all of Cinnamon integration...

Regards.

Regards.

**Comment by tista500** [comment]
I've committed for your 2nd issue, so check if this could solve... I really hope...

Regards.

**Comment by vibeast** [comment]
Still in nemo and gedit

**Comment by vibeast** [comment]
Don't give up the cinnamon :(

**Comment by tista500** [comment]
@vibeast,

OK.
I've reverted previous commit since it did not solve this issue.
And I can't fix any issues Cinnamon 2.8.x in this time, so please use other themes.

Regards.

**Comment by vibeast** [comment]
Ok, It's fine
Thanks for trying man.

**Comment by tista500** [comment]
@vibeast,

Today I've got some progess, so please check my `wip/revive_cinnamon` branch: https://github.com/tista500/Adapta/tree/wip/revive_cinnamon

I hope invisible button foreground issue would be fixed...

Regards.

**Comment by vibeast** [comment]
Flawless man.
Thank you !

![done](https://cloud.githubusercontent.com/assets/18408100/14504159/ecf8d9f0-0189-11e6-9d1a-8c170ae98166.png)

**Comment by tista500** [comment]
OK.
Closed...

Regards.
