### ISSUE TITLE
Maybe deincrease padding for maximized/tiled windows?

### ISSUE THREAD

**Issue by jhasse** [tista500/Adapta#50]
I'm using the [BottomPanel](https://extensions.gnome.org/extension/949/bottompanel/) GNOME Shell extension and always like to use the top edge to select buttons in the header bar of maximized / tiled windows. Unfortunately there is a small padding which doesn't allow me to click buttons in Gtk+ 3 applications which are using the GtkHeaderBar widget.

I've created a [bug report for Gtk](https://bugzilla.gnome.org/show_bug.cgi?id=758244), but so far no one has commented on that.

Do you know if that can be fixed easily by the theme? Maybe deincrease the padding for maximized and tiled windows?

**Comment by tista500** [comment]
@jhasse,

> always like to use the top edge to select buttons in the header bar of maximized / tiled windows

Why Gnome-Shell should mislead the button's clickable-area when miximized/tiled? Top-right hot-corner is not the clickable-area as default.
As I say, SSDs seems to have the misleading instead of CSDs, just on my Adapta. Since Adapta has paddings in both Mutter's titlebar and GtkHeaderBar...

> Do you know if that can be fixed easily by the theme? Maybe deincrease the padding for maximized and tiled windows?

In technically, that can be, but I don't want to do. In Gtk+ 3.20, paddings/margins are very important stuffs to construct element containers like GtkHeaderBars. Or more specific selector in CSS for `.titlebutton`?

Regards.

**Comment by jhasse** [comment]
I don't think it would be misleading, as we're talking about just a few pixels. Also SSD currently behave this way and I don't think anyone is complaining about that.

The thing is, that currently those few pixels around the close button have no real use (except for moving the window, but that's also possible with the close button). So I think it would be a good idea to expand the clickable area a bit, as it would make it a lot easier for me to hit the button. It would also help touch users a little bit to hit buttons in the GtkHeaderBar.

> In Gtk+ 3.20, paddings/margins are very important stuffs to construct element containers like GtkHeaderBars. Or more specific selector in CSS for .titlebutton?

So it isn't possible as of now without some kind of hack, right?

**Comment by tista500** [comment]
@jhasse,

No. it's completely misleading because in circle buttons, it becomes around 8 to 10 px in radius from the screen edge.

>  those few pixels around the close button have no real use

No. click/tap is not the only action but also hover. your opinion seems obviously ignores this. Few pixels are so small but so important and necessary.

> It would also help touch users a little bit to hit buttons in the GtkHeaderBar.

No. the mouse pointer needs more severe in spacing factors than finger tapping. On the other hand, fingers needs more spacing around the tapping-areas than pointers. I don't think the problems in tap is tappable-area size, but the distance from any other elements and/or screen edges. So I suppose such few pixels would not help for tap actions.

> So it isn't possible as of now without some kind of hack, right?

I don't know why you ask to me here... Was not it the answer already that nobody respond your post in bugzilla?

Here is not the right place to discuss about the features of Gtk+.

Regards.

**Comment by jhasse** [comment]
I understand your point: Decreasing the padding is not a good option.

> Here is not the right place to discuss about the features of Gtk+.

Sorry, I thought since you're doing this awesome theme, you might know more about the inner workings of Gtk and if this could be fixed on the CSS / theme side of things.
