### ISSUE TITLE
Just GTK

### ISSUE THREAD

**Issue by Fabiuz99** [tista500/Adapta#56]
Hi, I have installed Adapta as you have described in readme file.
However in this moment I'm not using Gnome so I need just the GTK theme. I want to ask you if the installer install just the GTK theme or the Gnome one too.

**Comment by tista500** [comment]
@Fabiuz99,

Sorry for my late reply...
Well, Adapta has been developed for Gnome-Shell from the start. So I have not any plans to provide this Gtk+ theming without Gnome-Shell theming. Because Adapta's goal is to provide fine user-experiences in GNOME desktop environment in newest release...

Now I didn't have any clue, but if you're the one of contributors, please do patchworks to `Makefile.am` meanwhile... Later I may or may not introduce such custom installer via configure options, regardless...

Regards.

**Comment by Fabiuz99** [comment]
Oook, thank you

**Comment by tista500** [comment]
@Fabiuz99,

I've introduced new configurable installer yesterday.
Now you can avoid installing Cinnamon, Unity and GNOME-Flashback with options:
```
./autogen.sh --disable-cinnamon --disable-flashback --disable-unity
```

But Adapta needs Gnome-Shell and Budgie so these are installed as default...

Regards.

**Comment by Fabiuz99** [comment]
Wow, thank you very much.
