### ISSUE TITLE
Lollypop issue.

### ISSUE THREAD

**Issue by m110s** [tista500/Adapta#58]
I've noticed that after some updates of adapta theme rendering of Lollypop is broken.
Adapta:
![screenshot from 2016-04-18 17-07-52](https://cloud.githubusercontent.com/assets/5939323/14609436/174bc18c-058a-11e6-976c-f72e39a3e22b.png)
Example of Flatplat theme:
![screenshot from 2016-04-18 17-08-09](https://cloud.githubusercontent.com/assets/5939323/14609451/259f56a4-058a-11e6-8346-83e8fb7805c2.png)
Arch aur package: adapta-gtk-theme 3.20.3.50, gnome 3.20.
Rendering was fine when I started to use adapta with gnome 3.20 and latest gtk3 3.20.3

**Comment by tista500** [comment]
@m110s,

Fix commit has been landed.
By the way, Flat-Plat does not have apps specific styling, but Adapta does. So Nemo styling conflicted  with Lollypop's `GtkWdget`. Both apps are messing me because those are not willing to convert to CSS nodes from widget's minor style-classes... :(

In Gtk+ 3.20, such minor style-classes are cancer...

Regards.
