### ISSUE TITLE
I can't see the text

### ISSUE THREAD

**Issue by victormoreira** [tista500/Adapta#6]
Hello @tista500 I'm a big fan of your theme, Your theme works perfect in Gnome, but in Cinnamon has a small defect in the text of a popup when "Adapta Light".

I'm sorry about my English, I'm using Google Translate :DD

![cinnamonissue](https://cloud.githubusercontent.com/assets/13660595/13302854/de6278e0-db2a-11e5-9a59-b4f6ed330005.jpg)

**Comment by djendreizak** [comment]
Well, as far as I know, Adapta is not optimized for Cinnamon (currently not a Cinnamon user).
 
Have look here: https://github.com/tista500/Adapta/issues/1

**Comment by tista500** [comment]
@victormoreira,
@djendreizak,

Yeah the Cinnamon integration is not started yet. In a couple of days I've seen some other Cinnamon themes, but I'm a bit busy now to polish up my 3.19.x branch for preparing Gtk+ 3.20.

It seems Cinnamon theming may need much more time to implement because most part of famous themes are created by pixmaps like png/svg, to be honest, I don't like such requirements if Cinnamon forced to do so...

Anyway today Adapta doesn't support Cinnamon desktop.

Regards.

**Comment by tista500** [comment]
Greetings,

Today I've committed Cinnamon 2.8.x desktop support, so please check if my theming could work as you guys expected (I did not test it well since Cinnamon is not my thing).

Regards.

**Comment by tista500** [comment]
Oh wait...

How to enable dark variant in Cinnamon? damned.

Reopen it.
