### ISSUE TITLE
A no Backdrop version

### ISSUE THREAD

**Issue by alex285** [tista500/Adapta#65]
Is it possible to offer an Adapta version without the backdrop on elements than titlebars?

**Comment by tista500** [comment]
@alex285,

No. Then what is the source of your suggestion/feature-request?
Until Material design polished 'Multiple window management' section, we should follow and obey the Gnome's HIG. It means I'm now keeping my eyes open carefully for the source of Adwaita and what Lapo is doing design in next Gnome 3.22 (actually 3.21.1)... In Material Design, next N release cycle would be the first turning point to employ multiple window management about 'unmaximzied' and 'tiled' actions/animations in active workspace, so that I will learn it from N cycle about backdrop state...

And maybe there will be some unacceptable/conflict parts between Gnome and Material Design (in technical side, or in design side) though, I now can't estimate what N cycle brings to us...

Regards.

**Comment by alex285** [comment]
The reasons I ask for no backdrop are:
1. I dont see any visual benefits plus there is not even proper support in GTK, so some elements get backdrop effect, others don't, and even in the first case things are ugly

2. One of the reasons I like Adapta it is because it "plays" good with other applications like Blender, Atom, and HTML5 apps. But none other has backdrop, so it just breaks the consistency.

Sure we can wait for next MD release to see how they will deal with unfocused windows, but honestly I find unlikely that the backdrop will be per element. Pretty sure it will be shadows on surfaces (or colors change), as it already happens with focus on drawers etc.

**Comment by tista500** [comment]
Ah OK.

I should keep your suggestion in my mind... ;)

Regards.
