### ISSUE TITLE
Display problem in firefox bookmarks toolbar

### ISSUE THREAD

**Issue by pevoz23** [tista500/Adapta#71]
**Reporter info**

 ```
 * Distribution - ubuntu gnome 16.04
 * Gtk+ version - gtk3: 3.18.9  // gtk2: 2.24.30
 * Desktop environment - gnome 3.18
 ```

**Adapta version (if you knew)**
3.21.1+git20160501-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
Mozilla Firefox 46.0

**Actual issue**
When hovering bookmarks items on the bookmarks toolbar of firefox, a shadow remains.
![screenshot from 2016-05-01 19-18-03](https://cloud.githubusercontent.com/assets/18751893/14943148/cba3dd76-0fd1-11e6-850c-dfd017f911a8.png)

**How to reproduce (if you knew)**
hover firefox bookmarks in the toolbar

**Expected behaviour**
Shadow should disappear

**Other Note (feature-request, question, etc...)**
Thanks for your impressive work!

**Comment by tista500** [comment]
@pevoz23,

I suppose that issue would be Firefox bug...
Because once I've tweaked Numix theme to add outset shadows around GtkButtons, that issue happened as well (in both FF 45 & 46).

And nana-4 already reported that issue: https://github.com/nana-4/Flat-Plat/issues/17
Indeed, Flat-Plat and Adapta have quite similar rendering method in GtkButton.

Anyway I'm going to track down this issue...

Regards.

**Comment by gregorydk** [comment]
Upgrading to Firefox 46.0.1 solves this.

**Comment by hadrien-psydk** [comment]
I am having this bug on Ubuntu 16.04 with Firefox 47.0 and the PPA version of Adapta. Should I open a new issue?

**Comment by tista500** [comment]
@hadrien-psydk,

It's completely upstream (firefox) issue, so I can't handle this.
