### ISSUE TITLE
Different colors for different apps

### ISSUE THREAD

**Issue by ManjaroCinnamonFan** [tista500/Adapta#74]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
Have you thought about doing something like the latest Paper-GTK-theme: changing the color-theme  for specific applications? Would it require allot of adjustments?

**Comment by tista500** [comment]
@ManjaroCinnamonFan,

Unfortunately I don't have any plans to allow to set application specific colours.
In Gtk+ 3.20 or higher, we've already moved to CSS node-based theming from style-classes. It means all of GtkWindow/GtkDialog was dealt with 'monolithic' `window/dialog` node, so that we can get lots of benefits to share base styling within various Gtk+ applications. On the other hand, as of Paper Gtk+ theme, 'application specific colour definition' seems to be the opposite side of Gtk+ development focus... In fact, current Paper might have some issues of such features in Gtk+ 3.20 and I don't know how developer is going to solve those issues via 'window' node.

However, in technically, I can set those 'colourful' GtkHeaderBars in case of Gtk+ 3.18 theming only. But I don't think it's good idea anyway. And in design side, Material Design never forces applications to wear 'colourful' window widgets, so please don't be confused like *colourful = Material Design*.

Finally, Gtk+ 3.22 will continue to enhance the employments of CSS nodes to follow up standardized CSS3 codebase, so application specific GtkHeaderBars will need Gtk+ upstream changes in future. And hacky tweaking Gtk+ theming will be wasting our precious time.

Regards.

**Comment by ManjaroCinnamonFan** [comment]
Okay,

I thought you wouldn't be interested.  I understand it is a dead end anyway.  

But some variation in colors would be welcome (that's Android speaking).  Not every application should be 'looking' the same for sake of 'consistency'.   I personally think colors makes the apps easily identifiable.  If you have a lots of windows open, the lack of 'difference' makes it difficult to pick the right window.   So it is a matter of opinion.  

You can give all the apps the same (unified) user-experience. On that I agree.  But letting them have 'identity', even if it is just a color, -that's basically Android's way- would be an interesting change in GTK-theming.  The Paper-theme at least tries to be. 

It would be interesting to find out if gnome-developers could make it possible to create something that would allow to easily change the colors of apps.  That it would be a CSS-setting you can easily change.       

Still, I like your work (have it running on Ubuntu Gnome 16.04), and I like the progress you have made. 
The maximize button is great! (it looks like some Chinese sign.) 
I know people seriously underestimate the work that you have to put in to it.  I, for one, am still using your theme on a daily basis. And it hasn't let me down yet. Thank you.

**Comment by tista500** [comment]
Indeed, if we had over 10 or 20 windows in a single workspace, it sometimes causes lack of focus.

Umm, we might need more time to wait until Gtk+ application developers could accept for CSS node-based styling worked properly with Gtk+ 3.2x since Gtk+ 3.20 was unveiled just in March. Some applications already have specific node name in its GtkWindow and/or GtkHeaderbar, if those trends spread out to most of Gtk+ 3.0 applications, we will be able to handle them via theming easily... Indeed, we surely need help and acceptance from application developers!

> The maximize button is great! (it looks like some Chinese sign.) 

The new maximize/unmaximize icon design is based on next Android N cycle's feature. But I've flipped maximize icon vertically because Android UI has a bottom-bar to contain window-switcher, on the other hand, lots of our Gtk+ based desktop environments now has top-bar as primary panel container as you guys know well. So Adapta's new maximize icon shows *max'd window frame and top-bar* (yeah it seems like east asian sign). Then unmaximize icon, it does *floating small window in desktop workspace*.

Those changes would be able to protect Adapta from changing icon theme pack, and keep Adapta's unique features ( to be honest, I could not accept for Paper's "plus" icon as maximize)...

Regards.

**Comment by Tadly** [comment]
A just slightly related question about coloring. (If you want that in a separate issue, lemme know and I'll create one)

Basically, I love this theme but am not to happy with the choice of colors (this is just personal preference, no offense!)
I remember that the someone created a tool (gtk-theme-config) which allowed to change some GTK colors (not sure if that still works these days).
I'm pretty sure this was a somewhat hacky way of doing things and didn't include e.g. gnome-shell.

So the question than, would it be possible, to specify a color palette / base and accent color at build time?

**Comment by tista500** [comment]
@Tadly,

There's no plans to provide to tweak colour scheme in user-side.
Because I have some reasons:
 * I can not guarantee unwanted user-level tweaks.
 * I will be wasting my time to track the issues down if uses had done tweaking in code bases.
 * In most cases, regardless users will break the Material Design colour palette, and once that happened, "unwanted" changes will be spread in DeviantArt, Gnome-Look and some other downstream sites. Those surely make me unhappy and then lose my motivations to develop.

In personal use, you should learn SASS/SCSS coding. I believe this is the most fastest way to handle Gtk+ theming as you like. Easy come easy go.

Reagads.

**Comment by Tadly** [comment]
@tista500 

Fair enough. Those are indeed valide points.
To bad there isn't an easy way to provide multiple color schemes as it is with android and the like (I think).

Some gnome/gtk themes come with multiple versions but I think that's a big overhead.
Oh well, thanks anyway :)

cheers

**Comment by tista500** [comment]
There's no big changes in upstream Gtk+ 3.22 development cycle today, so this time I close this...

Regards.
