### ISSUE TITLE
Bug circle week

### ISSUE THREAD

**Issue by Floflr** [tista500/Adapta#77]
Hello,
In the notification area of the circles surrounding the display weeks are not centered (see picture)

![bug week adapta](https://cloud.githubusercontent.com/assets/18467487/15091401/7c6f26e0-1448-11e6-8ba6-a14d17468fa0.png)

 ```
 Manjaro Gnome
 Gtk+ 3.20

**Comment by tista500** [comment]
@Floflr,

Partially confirmed.
Label spacing issue was fixed, but what is the 'grey circles'  in your shot? And let me know what's mean of your title 'bug circle week'...

Regards.

**Comment by Floflr** [comment]
@tista500 
Thank you for your prompt response
Yes with the last issue has disappeared. The circle are the rectangle in default theme (see picture)
![capture d ecran de 2016-05-07 15-49-43](https://cloud.githubusercontent.com/assets/18467487/15092497/03d4eaac-146c-11e6-8e0c-843d7277a971.png)
But it's a shame to have  removed the circle because it was easier to see the week in the calendar.

**Comment by tista500** [comment]
@Floflr,

> Yes with the last issue has disappeared.

Hey , where is the *first* issue? :(
And why didn't you follow the issue template? I'm really tired to asking tons of additional info to reporters, since poor reports could not help to track the issue down properly...

> But it's a shame to have removed the circle because it was easier to see the week in the calendar.

No. highlighted week numbers with lighter background colour were the bad design ideas in Material Design, and my design, too. If didn't like those, use other themes.

Regards.
