### ISSUE TITLE
Buttons in LO template management dialog hard to read

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#8]
See screenshot
![bildschirmfoto von 2016-02-25 12-47-35](https://cloud.githubusercontent.com/assets/1418818/13318911/11da42b4-dbbe-11e5-9e33-961a9ff905d1.png)

**Comment by tista500** [comment]
@HeikoAdams,

I now can confirm this issue.

Regards.

**Comment by tista500** [comment]
I"ve checked some other themes (Numix, Ark-Darker), and this also happens in such themes, So it might be the upstream bug (LibreOffice seems to draw that buttons with GtkMenuitem, indeed, it's completely non-sense and ugly)...

Meanwhile I won't force to fix it because it affects in other GtkMenubar elements.

Regards.

**Comment by zoutiyx** [comment]
@HeikoAdams @tista500 I couldn't see the pages numbers in Document Viewer (GNOME 3.18.3), but after one of the recent commits about 3 days ago, it was fixed. This issue was posted 5 days ago. Have you tried pulling the latest commit?

Just a suggestion...

**Comment by tista500** [comment]
@zoutiyx,

Thanks for your suggestion, but I could not fixed this issue yet.
Because this issue is related to GtkMenuBar instead of GtkHeaderBar (you had mentioned above). LibreOffice's Gtk+ 3.0 integration is really mad for many theme designer (this issue would happen in all of dark-menubar on light variant theme. so once switched to dark variant, such texts would be shown properly). This is completely upstream bug.

Regards.

**Comment by zoutiyx** [comment]
Oh. I now understand. Anyways I love the theme. I use Arch and it works
rather great.

On Tuesday, March 1, 2016, Tista <notifications@github.com> wrote:

> @zoutiyx <https://github.com/zoutiyx>,
>
> Thanks for your suggestion, but I could not fixed this issue yet.
> Because this issue is related to GtkMenuBar instead of GtkHeaderBar (you
> had mentioned above). LibreOffice's Gtk+ 3.0 integration is really mad for
> many theme designer (this issue would happen in all of dark-menubar on
> light variant theme. so once switched to dark variant, such texts would be
> shown properly). This is completely upstream bug.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tista500/Adapta/issues/8#issuecomment-190763895>.
>


-- 


___________________________________________________________________________________

Philan James

Software Engineer | Linux Enthusiast
___________________________________________________________________________________

**Comment by fitojb** [comment]
> LibreOffice seems to draw that buttons with GtkMenuitem

Yeah, please file a bug in https://bugs.documentfoundation.org and we’ll have a look. @caolanm is the main developer of the GTK+ integration component—he might be able to fix this when he’s got free time.
