### ISSUE TITLE
Nylas N1 theme

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#89]
Nylas N1 provide already a Ubuntu like theme.
I think it would be really cool to have a theme for that :)
Example of a theme : https://github.com/edipox/elementary-nylas

**Comment by tista500** [comment]
Hmm, smells MacOS... :(

By the way, that application could not support standard Gtk+ theming backend? I dislike that app because devs didn't concern the ARM 32bit architecture build/binary. Adapta needs to verify even on armhf/armel without any OpenGL/Mesa/DRM2 user-space graphic drivers.

So I won't install that app on my Intel 64bit architectures as well. Means "won't support".

Regards.

**Comment by bil-elmoussaoui** [comment]
It was just a proposition, i will close this then! Thanks for your great work :+1:
