### ISSUE TITLE
Suggested Action is the same color as Destructive Action

### ISSUE THREAD

**Issue by mmstick** [tista500/Adapta#99]
**Reporter Info**
I'm developing an application and notice that the colors for 'suggested-action' are the same as 'destructive-action' which makes the app a bit confusing. Here's how the colors look with Adwaita:

![adwaita colors](https://cloud.githubusercontent.com/assets/4143535/15379234/20541722-1d39-11e6-977a-cff46f31708b.png)

And then the colors with Adapta:

![adapta-colors](https://cloud.githubusercontent.com/assets/4143535/15379233/205335e6-1d39-11e6-856b-bf78708c3c24.png)

Is this on purpose?

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - GNOME Shell
 ```

**Adapta Version**
Adapta & Adapta Git

**Comment by tista500** [comment]
@mmstick,

Yep, Adapta follows my purpose exactly.
Because both 'destructive-action' and 'suggested-action' existed at the same time is rare case. Then in your case, we usually use a single "toggle" GtkButton includes such stop/start I think... 

In GtkHeaderBar, 1 single "Cancel" and 1 single "suggested" OR "destructive" are good...
![screenshot from 2016-05-19 11-41-48](https://cloud.githubusercontent.com/assets/6073622/15381025/c208b10e-1db6-11e6-9cc8-ae6daee48517.png)

If you could, please let me see the shot captured whole GtkWindow to learn why those 2 buttons should be existed at the same time in a single GtkWindw/GtkDialog...

Reagrds.

**Comment by mmstick** [comment]
The application's Systemd Units section displays a `MenuButton` for toggling between systemd unit types on the left pane, and on the right pane it provides a `Switch` to toggle the enablement status and a start and stop `Button` for starting/stopping services.

![screenshot from 2016-05-18 22-56-21](https://cloud.githubusercontent.com/assets/4143535/15381250/ddc5403a-1d4b-11e6-9e89-b8614bf7c94d.png)

**Comment by tista500** [comment]
@mmstick,

So where is the `systemctl restart` action?
If you would implement "restart" action as GtkButton in GtkPaned -> GtkHeaderBar, we need 3 GtkButtons...

Regards.

**Comment by mmstick** [comment]
The Rust application is still an ongoing WIP, but I plan to toggle the visibility of the Start and Stop buttons based on the context of the running status of the selected unit, and so adding another button to do the same thing would be redundant, but I can think about adding a Restart button alongside the Start button when the status is set to activated.

**Comment by mmstick** [comment]
Context-sensitive start/stop button has just been landed.

![screenshot from 2016-05-19 04-01-09](https://cloud.githubusercontent.com/assets/4143535/15386545/64ef2eac-1d76-11e6-9221-8efc49da7190.png)

**Comment by tista500** [comment]
If I were you, I will design like this:
![mockup](https://cloud.githubusercontent.com/assets/6073622/15389980/5a4788f4-1df4-11e6-852d-3a03c6e1aa4c.png)

This mockup has ugly spacing/geometry factors though, but anyway I believe it could show my opinion...

* 'suggested' and 'destructive' is the part of its GtkWindow, for example, usually such actions send `destroy` and/or `unref` calls to *its* GtkWindow/GtiDialog. But your approach seems just to notify users to deal with such buttons carefully. I don't think `systemctl start/stop` calls affect your GtkWindow's signals as well... So I suppose it's enough to preparing specific stylesheet for your application to costomize such action buttons appearance.

* GtkSwitch may be better to be placed in the left-side pane since mouse pointer traveling becomes  so long...

* Concern user's action and thinking more:
  1. search and find proper unit from left-side pane --- it strongly needs the way to"search" in the left-side pane.
  2. check that unit was enabled/disabled --- GtkSwitch should be placed near side of left-side pane to handle enabling/disabling.
  3. verify unit name in GtkHeaderBar --- center aligned `.title` class should be applied to show the GtkLabel of its unit name.
  4. if unit already run --- show only "restart" and "stop".
  5. if unit didn't run yet --- show only "start" and "restart", or just a single "start".
  6. users search configuration button --- need to put "open context-menu" or "open GtkPopover" to show the global setting of its applications (If it concerns Gnome-Shell, use AppMenu at the left-most side of GtkHeaderBar).

* I don't think it need the indicator for "not-running" units, but it should be decided by developers.

* Sometimes units remain the logs when launching, so it's better to indicate if any warnings/logs are existed (or hook gnome-logs to open logs).

* "save" button at the bottom of its GtkNotebook seems to be moved to header node.

Finally I haven't any necessities to use 'suggested' and/or 'destructive' action buttons. ;)

Regards.

**Comment by tista500** [comment]
@mmstick,

OK. New suggested-action colour has landed: https://github.com/tista500/Adapta/commit/3feae14fbab8d69a9d7e33b27aba722e908cdb97

This time I used famous "Teal" colour for suggestion... Hope this could help your development.

Regards.

**Comment by mmstick** [comment]
This does help a lot. The changes are now displayed in the latest screenshots for my project:
https://github.com/mmstick/systemd-manager
